.bin/msy: complete rewrite.

diff --git a/msy b/msy
--- a/msy
+++ b/msy
@@ -1,23 +1,38 @@
-#!/bin/sh -e
-####
-#### Strip the evil MS Word shite out of MSY's part list, thereby
-#### reducing the render time (e.g. in webkit or w3m) by an order of
-#### magnitude or more.
-{
-    echo '<html><body><table border="1" style="border-collapse: collapse">'
-    curl -sSf http://msy.com.au/Parts/PARTS_W.HTM |
-    iconv -c --from gb2312 | tr -d '\r' |
-    perl -p0 -e 's|<([^>[:space:]]+)[^>]*>|<$1>|g' | # strip line-spanning attributes
-    sed '1,/<table/d' | sed '1,/<table/d' | sed '/<\/table/,$d' | # extract second table
-    sed -r 's/&nbsp;/ /g' |       # whitespace sequences SHOULD be folded!
-    sed -r 's:</?([^/t]|t[^hrd])[^>]*>::g' # remove non-table elements
-    echo '</table></body></html>'
+#!/bin/bash
+set -eEu -o pipefail
+shopt -s failglob
+trap 'echo >&2 "$0:${LINENO}: unknown error"' ERR
+
+# MSY is a local computer parts retailer.
+# Their parts list is HTML generated by Microsoft Word,
+# and is notoriously slow to render in a browser.
+#
+# This script turns it into a simple line-delimited list,
+# to make grepping much easier.
+#
+# EXAMPLE:
+#
+#   msy >cache
+#   <cache foldr grep -i -- 2TB 3.5 7200 SATA
+#   <cache foldr grep -i -- Modular PSU [5-9]..W
+#
+# See also: http://www.accc.gov.au/search/accc-funnelback/MSY
+# See also: http://www.staticice.com.au/
+
+curl -sSf http://msy.com.au/Parts/PARTS_W.HTM |
+
+# tidy seems to struggle to convert the encoding,
+# so convert it in advance & then tell tidy to both read & write UTF-8.
+# The --to ascii//translit makes grepping for inches (") easier
+iconv -c --from gb2312 --to ascii//translit |
+sed 's/&nbsp;/ /' |             # Downgrade NBSP to CFWS.
+sed -r 's|<o:p> ?</o:p>||g' |   # Appease tidy.
+{   tidy -asxml --numeric-entities yes -utf8 -w 0 -q --show-warnings no ||
+    (($? == 1))                 # tidy warnings aren't fatal errors.
 } |
 
-# The LC_ALL=C uses ASCII instead of Unicode box drawing characters.
-# The -cols unwraps very long rows.
-LC_ALL=C w3m -T text/html -cols 512 |
-egrep -v '(NSW|QLD|SA).*Clearance' |
-sed -nr 's/.([^|]*)\|(.*).$/\2|\1/p' | tr -s '[:blank:]' | column -ts'|' |
-sort -nr
-
+sed '1,/^<html/c<html>' |       # Appease xmlstarlet (namespaces are annoying).
+xmlstarlet sel -T -t -m '//table[2]/tr' -v 'td[2]/p' -o ' ' -v 'td[1]/p' -nl |
+sort -rn |                      # Sort by descending price.
+numfmt --invalid=ignore --padding=5 --grouping
+#numfmt --invalid=ignore --padding=4 --to=si --round=up
